### ISSUE TITLE
Cursor position in the Edit view

### ISSUE THREAD

**Issue by dalnim** [farmery/FlutterEbookApp#14]
In Edit view, I tried to edit a meaning and tap at to end of meaning, but the cursor goes to the beginning of meaning. I have to tap at the end of meaning again. 

<img width="399" alt="image" src="https://github.com/farmery/FlutterEbookApp/assets/3542033/9f4faeae-fbd4-4639-bdd2-4d4573f5cb39">

**Comment by farmery** [comment]
ive fixed this issue
